### ISSUE TITLE
Help using libsofa.xcodeproj 

### ISSUE THREAD

**Issue by lmtanco** [sofacoustics/API_Cpp#3]
Hi there, 

I am working on a 3d audio project (http://3d-tune-in.eu) which will use Sofa as HRTF preferred format, so we have recently started to use your API. I have managed to compile the files in the C++ API, link them to the macos 3rd-party libraries you provide and to our test apps and it works great! :-) We are using the Listen HRTF database and used some of your matlab scripts to generate the sofa files. Thanks for the great work. 

I have now forked your API_Cpp repository with the plan to provide library-only projects, including Windows ones (and hopefully other platforms as well). We will then use the forked repository as submodule in other github projects that use your API (which will eventually be made public - they are private are the moment). 

However I am stuck with re-using your libsofa.xcproj - please bear with me as I am quite unexperienced with Xcode and macos developement. I am using Xcode 7.2.1 on a MacBook Pro with OS X 10.11.3.  
When I try to compile the files using the provided libsofa.xcodeproj, I get the error "**The run destination My Mac is not valid for Running the scheme 'sofaexamples'."** (with any of the schemes). I've googled this but none of the workarounds I've found work for me. 

I could create the library project files from scratch but I would prefer to modify your ones, which have obviously already worked for you, so that the forked repository is an incremental change from yours, so that it can be eventually pulled by you if you find it useful. 

Sorry for the long message, many thanks in advance and Best regards, 

Luis Molina-Tanco - University of Malaga.

**Comment by tcarpent** [comment]
Hi Luis,

Hum... this is weird.
I would suggest to re-create the schemes:
in Xcode, go to the "Product" menu, "Schemes", "Manage Schemes...",
then delete all existing schemes, then re-create them by clicking
"Autocreate Schemes Now".
Hopefully that should work.

Best regards

**Comment by lmtanco** [comment]
Thanks for the super-fast response, 
Tried it but unfortunately didn't make a difference :-(

**Comment by tcarpent** [comment]
Ah, OK :

in file libsofa.common.xconfig, add the following :
MACOSX_SDK_10_11                = $(DEVELOPER_SDK_DIR)/MacOSX10.11.sdk

and replace :
SDKROOT                         = $(MACOSX_SDK_10_10)
with :
SDKROOT                         = $(MACOSX_SDK_10_11)

SDK 10.10 is no longer shipped with your version of Xcode.

**Comment by lmtanco** [comment]
Yes!! That was it! Thank you so much!! :-) :-)
